// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type Dream struct {
	ID          string
	UserID      string
	Description string
	Explanation string
	Date        string
}

type Item struct {
	ID     int64
	Value  string
	ListID int64
}

type List struct {
	ID     int64
	Name   string
	UserID string
}

type User struct {
	ID           string
	Email        string
	Name         string
	HashPassword string
}
